export const NAMED_COLORS = [
  //Pink Colors
  { text: "Pink", value: "#FFC0CB", group: "Pink" },
  { text: "Light Pink", value: "#FFB6C1", group: "Pink" },
  { text: "Hot Pink", value: "#FF69B4", group: "Pink" },
  { text: "Deep Pink", value: "#FF1493", group: "Pink" },
  { text: "Pale Violet Red", value: "#DB7093", group: "Pink" },
  { text: "Medium Violet Red", value: "#C71585", group: "Pink" },

  //Purple Colors
  { text: "Lavender", value: "#E6E6FA", group: "Purple" },
  { text: "Thistle", value: "#D8BFD8", group: "Purple" },
  { text: "Plum", value: "#DDA0DD", group: "Purple" },
  { text: "Orchid", value: "#DA70D6", group: "Purple" },
  { text: "Violet", value: "#EE82EE", group: "Purple" },
  { text: "Fuchsia", value: "#FF00FF", group: "Purple" },
  { text: "Magenta", value: "#FF00FF", group: "Purple" },
  { text: "Medium Orchid", value: "#BA55D3", group: "Purple" },
  { text: "Dark Orchid", value: "#9932CC", group: "Purple" },
  { text: "Dark Violet", value: "#9400D3", group: "Purple" },
  { text: "Blue Violet", value: "#8A2BE2", group: "Purple" },
  { text: "Dark Magenta", value: "#8B008B", group: "Purple" },
  { text: "Purple", value: "#800080", group: "Purple" },
  { text: "Medium Purple", value: "#9370DB", group: "Purple" },
  { text: "Medium Slate Blue", value: "#7B68EE", group: "Purple" },
  { text: "Slate Blue", value: "#6A5ACD", group: "Purple" },
  { text: "Dark Slate Blue", value: "#483D8B", group: "Purple" },
  { text: "Rebecca Purple", value: "#663399", group: "Purple" },
  { text: "Indigo", value: "#4B0082", group: "Purple" },

  //Red Colors
  { text: "Light Salmon", value: "#FFA07A", group: "Red" },
  { text: "Salmon", value: "#FA8072", group: "Red" },
  { text: "Dark Salmon", value: "#E9967A", group: "Red" },
  { text: "Light Coral", value: "#F08080", group: "Red" },
  { text: "Indian Red", value: "#CD5C5C", group: "Red" },
  { text: "Crimson", value: "#DC143C", group: "Red" },
  { text: "Red", value: "#FF0000", group: "Red" },
  { text: "Fire Brick", value: "#B22222", group: "Red" },
  { text: "Dark Red", value: "#8B0000", group: "Red" },

  //Orange Colors
  { text: "Orange", value: "#FFA500", group: "Orange" },
  { text: "Dark Orange", value: "#FF8C00", group: "Orange" },
  { text: "Coral", value: "#FF7F50", group: "Orange" },
  { text: "Tomato", value: "#FF6347", group: "Orange" },
  { text: "Orange Red", value: "#FF4500", group: "Orange" },

  //Yellow Colors
  { text: "Gold", value: "#FFD700", group: "Yellow" },
  { text: "Yellow", value: "#FFFF00", group: "Yellow" },
  { text: "Light Yellow", value: "#FFFFE0", group: "Yellow" },
  { text: "Lemon Chiffon", value: "#FFFACD", group: "Yellow" },
  { text: "Light Golden Rod Yellow", value: "#FAFAD2", group: "Yellow" },
  { text: "Papaya Whip", value: "#FFEFD5", group: "Yellow" },
  { text: "Moccasin", value: "#FFE4B5", group: "Yellow" },
  { text: "Peach Puff", value: "#FFDAB9", group: "Yellow" },
  { text: "Pale Golden Rod", value: "#EEE8AA", group: "Yellow" },
  { text: "Khaki", value: "#F0E68C", group: "Yellow" },
  { text: "Dark Khaki", value: "#BDB76B", group: "Yellow" },

  //Green Colors
  { text: "Green Yellow", value: "#ADFF2F", group: "Green" },
  { text: "Chartreuse", value: "#7FFF00", group: "Green" },
  { text: "Lawn Green", value: "#7CFC00", group: "Green" },
  { text: "Lime", value: "#00FF00", group: "Green" },
  { text: "Lime Green", value: "#32CD32", group: "Green" },
  { text: "Pale Green", value: "#98FB98", group: "Green" },
  { text: "Light Green", value: "#90EE90", group: "Green" },
  { text: "Medium Spring Green", value: "#00FA9A", group: "Green" },
  { text: "Spring Green", value: "#00FF7F", group: "Green" },
  { text: "Medium Sea Green", value: "#3CB371", group: "Green" },
  { text: "Sea Green", value: "#2E8B57", group: "Green" },
  { text: "Forest Green", value: "#228B22", group: "Green" },
  { text: "Green", value: "#008000", group: "Green" },
  { text: "Dark Green", value: "#006400", group: "Green" },
  { text: "Yellow Green", value: "#9ACD32", group: "Green" },
  { text: "Olive Drab", value: "#6B8E23", group: "Green" },
  { text: "Dark Olive Green", value: "#556B2F", group: "Green" },
  { text: "Medium Aqua Marine", value: "#66CDAA", group: "Green" },
  { text: "Dark Sea Green", value: "#8FBC8F", group: "Green" },
  { text: "Light Sea Green", value: "#20B2AA", group: "Green" },
  { text: "Dark Cyan", value: "#008B8B", group: "Green" },
  { text: "Teal", value: "#008080", group: "Green" },

  //Cyan Colors
  { text: "Aqua", value: "#00FFFF", group: "Cyan" },
  { text: "Cyan", value: "#00FFFF", group: "Cyan" },
  { text: "Light Cyan", value: "#E0FFFF", group: "Cyan" },
  { text: "Pale Turquoise", value: "#AFEEEE", group: "Cyan" },
  { text: "Aquamarine", value: "#7FFFD4", group: "Cyan" },
  { text: "Turquoise", value: "#40E0D0", group: "Cyan" },
  { text: "Medium Turquoise", value: "#48D1CC", group: "Cyan" },
  { text: "Dark Turquoise", value: "#00CED1", group: "Cyan" },

  //Blue Colors
  { text: "Cadet Blue", value: "#5F9EA0", group: "Blue" },
  { text: "Steel Blue", value: "#4682B4", group: "Blue" },
  { text: "Light Steel Blue", value: "#B0C4DE", group: "Blue" },
  { text: "Light Blue", value: "#ADD8E6", group: "Blue" },
  { text: "Powder Blue", value: "#B0E0E6", group: "Blue" },
  { text: "Light Sky Blue", value: "#87CEFA", group: "Blue" },
  { text: "Sky Blue", value: "#87CEEB", group: "Blue" },
  { text: "Corn flower Blue", value: "#6495ED", group: "Blue" },
  { text: "Deep Sky Blue", value: "#00BFFF", group: "Blue" },
  { text: "Dodger Blue", value: "#1E90FF", group: "Blue" },
  { text: "Royal Blue", value: "#4169E1", group: "Blue" },
  { text: "Blue", value: "#0000FF", group: "Blue" },
  { text: "Medium Blue", value: "#0000CD", group: "Blue" },
  { text: "Dark Blue", value: "#00008B", group: "Blue" },
  { text: "Navy", value: "#000080", group: "Blue" },
  { text: "Midnight Blue", value: "#191970", group: "Blue" },

  //Brown Colors
  { text: "Cornsilk", value: "#FFF8DC", group: "Brown" },
  { text: "Blanched Almond", value: "#FFEBCD", group: "Brown" },
  { text: "Bisque", value: "#FFE4C4", group: "Brown" },
  { text: "Navajo White", value: "#FFDEAD", group: "Brown" },
  { text: "Wheat", value: "#F5DEB3", group: "Brown" },
  { text: "Burly Wood", value: "#DEB887", group: "Brown" },
  { text: "Tan", value: "#D2B48C", group: "Brown" },
  { text: "Rosy Brown", value: "#BC8F8F", group: "Brown" },
  { text: "Sandy Brown", value: "#F4A460", group: "Brown" },
  { text: "Golden Rod", value: "#DAA520", group: "Brown" },
  { text: "Dark Golden Rod", value: "#B8860B", group: "Brown" },
  { text: "Peru", value: "#CD853F", group: "Brown" },
  { text: "Chocolate", value: "#D2691E", group: "Brown" },
  { text: "Olive", value: "#808000", group: "Brown" },
  { text: "Saddle Brown", value: "#8B4513", group: "Brown" },
  { text: "Sienna", value: "#A0522D", group: "Brown" },
  { text: "Brown", value: "#A52A2A", group: "Brown" },
  { text: "Maroon", value: "#800000", group: "Brown" },

  //White Colors
  { text: "White", value: "#FFFFFF", group: "White" },
  { text: "Snow", value: "#FFFAFA", group: "White" },
  { text: "Honey Dew", value: "#F0FFF0", group: "White" },
  { text: "Mint Cream", value: "#F5FFFA", group: "White" },
  { text: "Azure", value: "#F0FFFF", group: "White" },
  { text: "Alice Blue", value: "#F0F8FF", group: "White" },
  { text: "Ghost White", value: "#F8F8FF", group: "White" },
  { text: "White Smoke", value: "#F5F5F5", group: "White" },
  { text: "Sea Shell", value: "#FFF5EE", group: "White" },
  { text: "Beige", value: "#F5F5DC", group: "White" },
  { text: "Old Lace", value: "#FDF5E6", group: "White" },
  { text: "Floral White", value: "#FFFAF0", group: "White" },
  { text: "Ivory", value: "#FFFFF0", group: "White" },
  { text: "Antique White", value: "#FAEBD7", group: "White" },
  { text: "Linen", value: "#FAF0E6", group: "White" },
  { text: "Lavender Blush", value: "#FFFFFF", group: "White" },
  { text: "Misty Rose", value: "#FFE4E1", group: "White" },
  { text: "Clear", value: "transparent", group: "White" },

  //Grey Colors
  { text: "Gainsboro", value: "#DCDCDC", group: "Grey" },
  { text: "Light Gray", value: "#D3D3D3", group: "Grey" },
  { text: "Silver", value: "#C0C0C0", group: "Grey" },
  { text: "Dark Gray", value: "#A9A9A9", group: "Grey" },
  { text: "Dim Gray", value: "#696969", group: "Grey" },
  { text: "Gray", value: "#808080", group: "Grey" },
  { text: "Light Slate Gray", value: "#778899", group: "Grey" },
  { text: "Slate Gray", value: "#708090", group: "Grey" },
  { text: "Dark Slate Gray", value: "#2F4F4F", group: "Grey" },
  { text: "Black", value: "#000000", group: "Grey" },
];

export const allowedFilters = [
  "material",
  "hingeType",
  "colorGroup",
  "frameShape",
  "frameType",
];
